[이은영-team1] Assignment2 : Express API - 유저 회원가입 하기
wecode-bootcamp-korea/39-backend-westagram-1 pull request #14
Opened 2022-11-03 07:50 UTC by exnyxxng

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
- 사용할 ID, 비밀번호, 이름, 이메일, 이미지 등록 가능
- 회원가입 성공시 상태코드 201, userCreated! 메세지 반환
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 수정사항 없음

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-03 07:53 UTC, exnyxxng commented
<img width="918" alt="스크린샷 2022-11-03 오후 4 04 22" src="https://user-images.githubusercontent.com/107943132/199670445-64d833ab-ac7c-4c7b-b85d-b08dc586ccc1.png">

DB에 잘 저장되었습니다.

2022-11-03 07:59 UTC, bigfanoftim requested changes

2022-11-03 07:59 UTC, bigfanoftim commented on eunyoung/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- `schema.sql`은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 `.gitignore`에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-11-03 08:20 UTC, bigfanoftim requested changes

2022-11-03 08:20 UTC, bigfanoftim commented on eunyoung/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- 개발을 하다보면 해당 브랜치에서 본인이 어떤 작업을 진행했는지 전부 다 기억할 수는 없습니다.
- 테스트 용으로 추가한 코드가 있을 수도 있고, 그 과정에서 미처 지우지 못한 불필요한 코드가 남아 있을 수 있습니다.
- 따라서 PR을 올리신 후에는 반드시 PR에 있는 `Files changed` 탭을 눌러 본인이 의도한 방향으로 코드가 잘 작성되었는지 확인해야 합니다.
- PR 올리기 전 각자 사용하고 있는 IDE(Vim, Vscode, WebStrom, IntelliJ 등)에서 Git 변경 사항을 체크하는 것도 좋은 방법입니다.


- 추가로 `.gitignore`에 등록하기 전에 한번이라도 Git으로 관리(add, commit 등)된 파일은 계속해서 Git에 의해 추적됩니다.
- 따라서 이를 해결하기 위해서는 다음과 같이 Git의 캐시를 삭제해야 합니다.
    - `git rm —cached 파일명`
- 삭제 후에는 수정된 사항을 다시 리모트에 푸시해야 합니다.

2022-11-03 08:20 UTC, exnyxxng commented
.gitignore에 추가완료했습니다 🙂 깃 너무 어려워요... 흙흙.. 모래모래... 자갈자갈...

2022-11-03 09:18 UTC, bigfanoftim commented
> .gitignore에 추가완료했습니다 🙂 깃 너무 어려워요... 흙흙.. 모래모래... 자갈자갈...

ㅋㅋㅋ ㅠ_ㅠ 지금은 좀 어려울 수 있겠지만 2개월차만 되어도 뚝딱뚝딱 하실겁니다~!

2022-11-03 09:19 UTC, bigfanoftim requested changes

2022-11-03 09:19 UTC, bigfanoftim commented on eunyoung/app.js
> +    const { user_id, password, name, email, user_img } = req.body
```suggestion
    const { userId, password, name, email, userImage } = req.body
```

- JavaScript에서는 기본적으로 `snake_case`가 아닌 `CamelCase`로 작성합니다.
- 또한 snake_case, CamelCase를 뒤죽박죽 섞어서 사용하면 안됩니다.
- 하나의 컨벤션으로 통일해서 작성해 주세요.

2022-11-04 02:05 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-04 02:05 UTC, merged