[박상욱-team1] Assignment1 : Express API - 초기 환경 세팅
wecode-bootcamp-korea/39-backend-westagram-1 pull request #16
Opened 2022-11-03 09:36 UTC by pso0301

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-03 10:32 UTC, bigfanoftim requested changes

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/.env.sample
> +DATABASE_URL = URL
```suggestion
```
중복인 것 같습니다.

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/db/migrations/20221103072455_create_authors_table.sql
> +-- migrate:up
- 과제와 상관없거나 해당되지 않는 코드가 Push 되었습니다. 이후 과제에서 진행되는 코드는 그 과제에 맞는 PR에서 Push 해주세요.

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/.env.sample
> +TYPEORM_PORT = 3306
sample인데도 불구하고 값이 다 들어와 있네요. sample에는 진짜 값을 넣지 말고 유추할 수 있는 데이터만 넣어주세요.

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/app.js
> +//
- 불필요한 주석은 삭제해주세요!

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/app.js
> +
```suggestion
```

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/app.js
> +//로깅메세지가 나오지 않습니다.
- 불필요한 주석은 삭제해주세요!
- 코드에 대한 설명을 주석으로 남겨놓고 싶어서 주석을 달게 되는 것은 처음에는 좋아보일 수는 있으나 나중에 코드에 수정이 발생했을 때 설명하는 주석까지 같이 수정하는 것을 놓치게 된다면 결국 설명 주석과 코드의 내용이 달라지고 오히려 더 유지보수하기 힘들게 될 수 있습니다.
- 주석으로 코드를 설명하기보다는 코드 자체의 가독성이 좋게만들어서 부가적인 설명이 필요없는 코드로 만들어주세요!

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/app.js
> +// const { start } = require("repl");
이런 것은 프로젝트에 사용되는 코드에 적기 보다는 개인 메모에 작성하는 것이 좋아보입니다.

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/app.js
> +
- 불필요한 줄바꿈이 많습니다. 전부 지워주세요.
- 개발을 하다보면 해당 브랜치에서 본인이 어떤 작업을 진행했는지 전부 다 기억할 수는 없습니다.
- 테스트 용으로 추가한 코드가 있을 수도 있고, 그 과정에서 미처 지우지 못한 불필요한 코드가 남아 있을 수 있습니다.
- 따라서 PR을 올리신 후에는 반드시 PR에 있는 `Files changed` 탭을 눌러 본인이 의도한 방향으로 코드가 잘 작성되었는지 확인해야 합니다.
- PR 올리기 전 각자 사용하고 있는 IDE(Vim, Vscode, WebStrom, IntelliJ 등)에서 Git 변경 사항을 체크하는 것도 좋은 방법입니다.

2022-11-03 10:32 UTC, bigfanoftim commented on sanguk/app.js
> +//health check
```suggestion
```

2022-11-03 11:53 UTC, pso0301 commented on sanguk/.env.sample
> +TYPEORM_PORT = 3306
관련 내용에 대해서 추상적으로 작성하였습니다.

2022-11-03 11:53 UTC, pso0301 commented on sanguk/db/migrations/20221103072455_create_authors_table.sql
> +-- migrate:up
dbmate 관련하여 내용 정리 하였습니다^^

2022-11-03 11:53 UTC, pso0301 commented on sanguk/.env.sample
> +DATABASE_URL = URL
수정 하였습니다.

2022-11-03 11:54 UTC, pso0301 commented on sanguk/app.js
> +
앞으로 필요 없는 부분에 대해 기억하도록 하겠습니다^^

2022-11-03 11:54 UTC, pso0301 commented on sanguk/app.js
> +//로깅메세지가 나오지 않습니다.
감사합니다. 다시 한번 확인 해보겠습니다.^^

2022-11-04 02:04 UTC, bigfanoftim approved these changes

2022-11-04 02:04 UTC, merged