[오현상-team1] Assignment 5~8 : Express API - 전체 게시글 조회하기]
wecode-bootcamp-korea/39-backend-westagram-1 pull request #17
Opened 2022-11-03 11:21 UTC by MatheGoD

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Assignment 5 ~ 8 과제 제출
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Assignment 5 : 특정 유저의 게시글 조회 (req.params로 요청 들어온 값을 변수에 할당해서 데이터를 불러온 후 결합)
- Assignment 6 : 게시글 수정 (app.patch, UPDATE를 사용해서 테이블 내 데이터를 수정해서 수정된 데이터를 호출)
- Assignment 7 : 게시글 삭제 (app.delete 와 DELETE를 사용하여 테이블 내 게시글 삭제)
- Assignment 8 : 좋아요 누르기 (특정 유저아이디와 포스트 아이디를 갖고 와서 만약 좋아요 테이블 내에 값이 존재하지 않을 시, 데이터에 삽입되어 좋아요를 누른 것 처럼 표현하고 만약 있으면 입력된 값을 삭제해 좋아요 취소와 동일하게 구현)
 
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-04 05:23 UTC, bigfanoftim requested changes

2022-11-04 05:23 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +});
[SQL Advanced](https://www.notion.so/wecode/SQL-SQL-Advanced-386ac13ca3034cb1becfa1efe8716606) 자료를 참고하여 하나의 Query문에서 JOIN을 사용하여 해결해 보세요.

2022-11-04 05:23 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  );
- 존재 여부만 판단하는 로직에는 `SELECT EXISTS` 문을 활용해 보세요.

2022-11-04 05:23 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +        post_id
프로젝트 전반적으로 들여쓰기를 2칸으로 맞추고 계신 것 같으니 그것과 동일하게 진행해 주세요~
```suggestion
      id,
      user_id,
      post_id
```

2022-11-04 05:23 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +        WHERE user_id = ${userId} and post_id =${postId}`
어디는 `? 표시`로 쿼리를 작성하고 다른 곳은 `$ 사인`으로 처리하셨는데 통일하는 것이 좋습니다.
또한 어느 것으로 통일해야 할지 의사 결정 하기 위해서는 그에 대한 충분한 근거가 필요합니다.

**Node.js**에서 **mysql driver**를 사용하여 **Raw SQL Query**를 작성할 때 ?를 왜 사용하는지 한번 구글링하여 찾아보시면 좋을 것 같습니다.

2022-11-04 05:23 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  const { title, content, image_url } = req.body;
수정하려고 하는 게시글이 존재하는지 검증하는 로직도 있으면 좋을 것 같습니다.

2022-11-04 05:23 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  const { postId } = req.body;
여기도 마찬가지로 검증하는 로직이 있으면 좋을 것 같습니다.

2022-11-04 05:45 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +});
!!! 해보겠습니다 !!!

2022-11-04 05:48 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +        post_id
세심한 개발자로..얼른 성장하겠습니다!

2022-11-05 05:06 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +  );
SELELCT EXISTS  사용 변수 할당 -> RowDataPacket 형태로 추출 -> 변수 선언 및 할당을 다시 하기보단 직접 접근해서 if 문을 적용 LIKES 와 DISLIKES를 구현했습니다.

2022-11-05 05:37 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +  const { title, content, image_url } = req.body;
네 알겠습니다!

2022-11-05 05:53 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +  const { postId } = req.body;
네 추가했습니다.

2022-11-05 07:44 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +        WHERE user_id = ${userId} and post_id =${postId}`
JS의 literal notation으로 쓰이는 **$ 사인**에서 -> **?란 Prepared Statement (PLACE HOLDER)**로 변경하였습니다. 
변경 사유
1.  오버헤드(처리시간) 감소
2.  데이터베이스에 침입하여 INPUT 값에 영향을 주는 MySQL INJECTION을 방어

2022-11-05 08:53 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +});
GROUP BY / JSON_ARRAYAAG / SUB-QUERY 사용해서 적용해보려고 합니다.

2022-11-05 09:05 UTC, MatheGoD commented
수정된 작업 내용 
1. SELECT EXISTS QUERY 사용
 - 특정 게시물의 수정/좋아요 그리고 삭제에서 사용자의 입력 값 검토
 
 2.  들여쓰기 수정
 
 3. ${} -> Prepared Statment : Placeholder = ? 로 통일
 - 처리 속도 및 보안을 위한 선택
 
 4. 특정 유저 게시물 조회 단일 QUERY로 변경
 Q : 현재 동기의 말을 듣고 MySQL2로 변경하였으나 계속 스트링 처리가 납니다. 프로그램의 문제일까요?
 
수정 완료

질문 :  게시글 수정에 해당 게시글이 존재하는지에 대한 로직은 구현했습니다만 실제 API구현 시 정말 필요한 로직인 것인가요? 실제로 게시글 수정을 하기 위해서는 본인의 게시글에 접근을 해야 하는데 일반적인 웹 상에서는 자기가 쓴 게시글은 이미 "보여지는" 상태이며 수정 버튼을 누를 수 있도록 되어 있습니다 . 아니면 저 로직으로 인해서 '수정'버튼이 활성화 되는 것인가요? 그것도 아니라면 최초 로그인시 토큰 값이 액세스 가능한 웹페이지 전반에 '적용'이 되기 때문에 로그인시 접근 가능한 모든 부분이 활성화 되는 것인가요?

2022-11-07 04:35 UTC, MatheGoD commented
const result = userPost.map((userPost) => ({
    ...userPost,
    postings: JSON.parse(userPost.postings),
  }));
  
  우선 5번 문제 단일 쿼리로 작성시 스트링으로 출력하는 것에 대해서는 동기분의 조언에 따라 다른 멘토님께서 작성해주신 법을 적용은 했습니다. 이렇게 하니 정상적으로 데이터가 출력이 되었습니다.

2022-11-07 05:27 UTC, bigfanoftim commented
> 현재 동기의 말을 듣고 MySQL2로 변경하였으나 계속 스트링 처리가 납니다. 프로그램의 문제일까요?

현상님~! 해당 문제는 nodemon 버전 문제로 생각이 되는데 한번 `node app.js` 명령어로 서버 실행 후 확인해보시겟어요?
만약 nodemon 문제라면 nodemon 버전을 다운그레이드하고 진행해 주세요~

2022-11-07 05:38 UTC, bigfanoftim commented
> 게시글 수정에 해당 게시글이 존재하는지에 대한 로직은 구현했습니다만 실제 API구현 시 정말 필요한 로직인 것인가요? 실제로 게시글 수정을 하기 위해서는 본인의 게시글에 접근을 해야 하는데 일반적인 웹 상에서는 자기가 쓴 게시글은 이미 "보여지는" 상태이며 수정 버튼을 누를 수 있도록 되어 있습니다 . 아니면 저 로직으로 인해서 '수정'버튼이 활성화 되는 것인가요? 그것도 아니라면 최초 로그인시 토큰 값이 액세스 가능한 웹페이지 전반에 '적용'이 되기 때문에 로그인시 접근 가능한 모든 부분이 활성화 되는 것인가요?

우선 토큰과는 상관이 없으며 그에 대한 내용은 `인증 & 인가` 세션을 통해 더 자세히 다뤄볼테니 잠시 미뤄두기로 하고, 검증하는 로직이 꼭 필요한지 따져본다면 제가 개발하는 서비스라면 저는 검증을 할 것 같아요. 

간단하게 예를 들어 사용자가 크롬 브라우저에 두 개의 탭을 켜고 있습니다. 첫 번째 탭에는 1번 게시판의 게시글 목록 페이지, 두 번째 탭에는 1번 게시판의 1번 게시글 페이지가 보입니다. 어떠한 이유로 사용자가 1번 게시판을 삭제합니다. 그리고 두 번째 탭에 있는 1번 게시판의 1번 게시글을 삭제하려고 API를 호출하게 되면 어떤 문제가 발생할까요?

우선 가장 먼저 없는 게시글을 삭제하려고 하니 query 문에서 에러가 발생할겁니다. 개발자가 어떤 게시글을 삭제하려고 하는지를 검증하지 않으면 위와 비슷한 상황에서 알 수 없는 에러가 발생하겠죠. 검증하는 로직이 있다면 DELETE 쿼리문을 실행하기 전에 각 상황에 맞는 검증 로직을 거친 후에 그에 맞는 에러 메세지를 건네 사용자가 `Server Error 500`와 같은 사용자가 볼 필요가 없는 에러가 아니라 `삭제된 게시글입니다.`와 같은  좀 더 정확한 메세지를 전달 받을 수 있을 것입니다.

2022-11-07 05:42 UTC, bigfanoftim requested changes
전체적으로 202가 쓰여져 있는데 어떤 이유로 쓰신건지 알 수 있을까요?

2022-11-07 05:42 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +    res.status(202).json({ message: "likeCreated" });
202 status code는 의도하신게 맞을까요?

2022-11-07 05:42 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +app.patch("/update/:postId", async (req, res, next) => {
- 이미 Patch 메소드 이름에 충분히 의미가 부여되었으니 URI는 요청에 맞는 자원을 기준으로 작성해 주세요.
- 또한 어떤 아이디를 업데이트하는지 자원이 명확해야 합니다.
    
    ```jsx
    // BAD ❌
    PATCH :3000/update/1
    
    // GOOD ✅
    PATCH :3000/post/1
    ```

2022-11-07 05:51 UTC, MatheGoD commented
> > 게시글 수정에 해당 게시글이 존재하는지에 대한 로직은 구현했습니다만 실제 API구현 시 정말 필요한 로직인 것인가요? 실제로 게시글 수정을 하기 위해서는 본인의 게시글에 접근을 해야 하는데 일반적인 웹 상에서는 자기가 쓴 게시글은 이미 "보여지는" 상태이며 수정 버튼을 누를 수 있도록 되어 있습니다 . 아니면 저 로직으로 인해서 '수정'버튼이 활성화 되는 것인가요? 그것도 아니라면 최초 로그인시 토큰 값이 액세스 가능한 웹페이지 전반에 '적용'이 되기 때문에 로그인시 접근 가능한 모든 부분이 활성화 되는 것인가요?
> 
> 우선 토큰과는 상관이 없으며 그에 대한 내용은 `인증 & 인가` 세션을 통해 더 자세히 다뤄볼테니 잠시 미뤄두기로 하고, 검증하는 로직이 꼭 필요한지 따져본다면 제가 개발하는 서비스라면 저는 검증을 할 것 같아요.
> 
> 위의 상황을 설명하기 위해 정확한 예시가 아닐 수 있으나 이해를 돕기 위해 예시를 하나 들어보겠습니다. 예를 들어 사용자가 크롬 브라우저에 두 개의 탭을 켜고 있습니다. 첫 번째 탭에는 1번 게시판의 게시글 목록 페이지, 두 번째 탭에는 1번 게시판의 1번 게시글 페이지가 보입니다. 어떠한 이유로 사용자가 1번 게시판을 삭제합니다. 그리고 두 번째 탭에 있는 1번 게시판의 1번 게시글을 삭제하려고 API를 호출하게 되면 어떤 문제가 발생할까요?
> 
> 우선 가장 먼저 없는 게시글을 삭제하려고 하니 query 문에서 에러가 발생할겁니다. 개발자가 어떤 게시글을 삭제하려고 하는지를 검증하지 않으면 위와 비슷한 상황에서 알 수 없는 에러가 발생하겠죠. 검증하는 로직이 있다면 DELETE 쿼리문을 실행하기 전에 각 상황에 맞는 검증 로직을 거친 후에 그에 맞는 에러 메세지를 건네 사용자가 `Server Error 500`와 같은 사용자가 볼 필요가 없는 에러가 아니라 `삭제된 게시글입니다.`와 같은 좀 더 정확한 메세지를 전달 받을 수 있을 것입니다.

2022-11-07 05:56 UTC, MatheGoD commented
> > 게시글 수정에 해당 게시글이 존재하는지에 대한 로직은 구현했습니다만 실제 API구현 시 정말 필요한 로직인 것인가요? 실제로 게시글 수정을 하기 위해서는 본인의 게시글에 접근을 해야 하는데 일반적인 웹 상에서는 자기가 쓴 게시글은 이미 "보여지는" 상태이며 수정 버튼을 누를 수 있도록 되어 있습니다 . 아니면 저 로직으로 인해서 '수정'버튼이 활성화 되는 것인가요? 그것도 아니라면 최초 로그인시 토큰 값이 액세스 가능한 웹페이지 전반에 '적용'이 되기 때문에 로그인시 접근 가능한 모든 부분이 활성화 되는 것인가요?
> 
> 우선 토큰과는 상관이 없으며 그에 대한 내용은 `인증 & 인가` 세션을 통해 더 자세히 다뤄볼테니 잠시 미뤄두기로 하고, 검증하는 로직이 꼭 필요한지 따져본다면 제가 개발하는 서비스라면 저는 검증을 할 것 같아요.
> 
> 위의 상황을 설명하기 위해 정확한 예시가 아닐 수 있으나 이해를 돕기 위해 예시를 하나 들어보겠습니다. 예를 들어 사용자가 크롬 브라우저에 두 개의 탭을 켜고 있습니다. 첫 번째 탭에는 1번 게시판의 게시글 목록 페이지, 두 번째 탭에는 1번 게시판의 1번 게시글 페이지가 보입니다. 어떠한 이유로 사용자가 1번 게시판을 삭제합니다. 그리고 두 번째 탭에 있는 1번 게시판의 1번 게시글을 삭제하려고 API를 호출하게 되면 어떤 문제가 발생할까요?
> 
> 우선 가장 먼저 없는 게시글을 삭제하려고 하니 query 문에서 에러가 발생할겁니다. 개발자가 어떤 게시글을 삭제하려고 하는지를 검증하지 않으면 위와 비슷한 상황에서 알 수 없는 에러가 발생하겠죠. 검증하는 로직이 있다면 DELETE 쿼리문을 실행하기 전에 각 상황에 맞는 검증 로직을 거친 후에 그에 맞는 에러 메세지를 건네 사용자가 `Server Error 500`와 같은 사용자가 볼 필요가 없는 에러가 아니라 `삭제된 게시글입니다.`와 같은 좀 더 정확한 메세지를 전달 받을 수 있을 것입니다.

자세한 답변 감사합니다~ 확실히 이해되었습니다! 확실히 제 습관과 성향이 잘 반영되어진 질문이었네요 ㅎㅎ

2022-11-07 06:01 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +    res.status(202).json({ message: "likeCreated" });
아...제가 202 STAUS CODE를 적용한 이유가 원래는  Accepted 즉, "사용자의 요청이 정상적으로 반영되었다"라는 것으로 해석하고 적용 했었는데 지금 와서 문서를 쭉 읽어보고 깨달았습니다..

202 STATUS CODE는 사용자의 요청이 반영되었으나 아직 진행 중일 때 쓰이는 것이군요...status code를 전반적으로 수정 해야 될 것 같습니다. 201이 더 적절한 코드인 것 같습니다.

2022-11-07 06:05 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +app.patch("/update/:postId", async (req, res, next) => {
네 알겠습니다! 

네이밍에 궁금한 것이 있습니다. 

patch가 적용되었다는 것은 저희가 코드를 보았을 때 알 수 있으나 사용자의 입장에서는 패치코드를 보는 것이 아니라서 네이밍을 저렇게 했습니다. '수정' 관련 부분은 프론트에서 버튼이나 ui로 구현하니깐 굳이 안해도 되는 것인가요?

2022-11-07 06:23 UTC, MatheGoD commented
> > 현재 동기의 말을 듣고 MySQL2로 변경하였으나 계속 스트링 처리가 납니다. 프로그램의 문제일까요?
> 
> 현상님~! 해당 문제는 nodemon 버전 문제로 생각이 되는데 한번 `node app.js` 명령어로 서버 실행 후 확인해보시겟어요? 만약 nodemon 문제라면 nodemon 버전을 다운그레이드하고 진행해 주세요~

node app.js로 실행해 보았지만 여전히 스트링으로 나오고 nodemon 버전을 2.0.15로 다운그레이드 해서 실행했지만 여전히 스트링으로 나와 우선 다시 최신 버전으로 업그레이드 후 로직을 추가해 스트링을 변환해서 출력 되게 변경했습니다.

2022-11-07 06:29 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +app.patch("/update/:postId", async (req, res, next) => {
사용자는 페이지 주소를 볼 수는 있으나 백엔드의 주소를 보지는 않기 떄문에 해당 URI는 개발자끼리 소통하는 주소라고 보시면 되겠습니다~

2022-11-07 06:29 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +app.patch("/update/:postId", async (req, res, next) => {
>  '수정' 관련 부분은 프론트에서 버튼이나 ui로 구현하니깐 굳이 안해도 되는 것인가요?

👍

2022-11-07 06:30 UTC, bigfanoftim commented
> node app.js로 실행해 보았지만 여전히 스트링으로 나오고 nodemon 버전을 2.0.15로 다운그레이드 해서 실행했지만 여전히 스트링으로 나와 우선 다시 최신 버전으로 업그레이드 후 로직을 추가해 스트링을 변환해서 출력 되게 변경했습니다.

쿼리 호출 결과를 내가 다시 파싱하는 것은 상황에 따라 다르겠지만 지금의 상황에서는 너무나 불필요한 요소라서 해당 부분은 같이 한번 살펴볼 필요가 있겠네요~ 우선 이대로 진행해주세요~!

2022-11-07 06:30 UTC, bigfanoftim commented
남긴 커멘트 다 확인하시면 다시 라벨 변경해주세요~!

2022-11-07 06:42 UTC, MatheGoD commented
> Member

전부 확인 했습니다~ 감사합니다.

2022-11-07 06:49 UTC, bigfanoftim approved these changes

2022-11-07 06:49 UTC, merged