과제1
wecode-bootcamp-korea/39-backend-westagram-1 pull request #2
Opened 2022-11-01 06:26 UTC by applleeee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-01 08:59 UTC, bigfanoftim reviewed
- PR 타이틀 혹은 설명 부분을 보다 상세하게 작성해 주세요.
- 구현 사항을 자세히 적으면서 본인이 어떻게 구현했는지 스스로 이해도를 점검해 볼 수 있으며, 나중에 내가 어떤 고민을 하고 어떻게 문제를 해결했는지 회고해 볼 수 있는 좋은 자산이 됩니다.

2022-11-01 09:10 UTC, bigfanoftim commented on songhyun/.env.sample
> +TYPEORM_LOGGING = TRUE
- 프로젝트에서 dbmate를 사용하여 스키마를 관리하기 때문에 이왕 sample을 구성했다면 dbmate에 관련된 환경 변수에 대한 가이드도 추가되면 좋을 것 같습니다.
    
    ```jsx
    DATABASE_URL="mysql://DB_USER:DB_PASSWORD@DB_HOST:DB_PORT/DB_NAME"
    ...
    ```

2022-11-02 04:52 UTC, bigfanoftim requested changes

2022-11-02 04:52 UTC, bigfanoftim commented on songhyun/db/migrations/20221102034908_users.sql
> +-- migrate:up
- 과제와 상관없거나 해당되지 않는 코드가 Push 되었습니다. 이후 과제에서 진행되는 코드는 그 과제에 맞는 PR에서 Push 해주세요.

2022-11-02 04:52 UTC, bigfanoftim commented on songhyun/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- `schema.sql`은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 `.gitignore`에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-11-02 05:46 UTC, applleeee commented on songhyun/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
gitignore에는 해당 파일을 추가해서 다시 push했는데 이미 올라가 있는 파일은 File changed에서 직접 삭제하면 될까요?

2022-11-02 05:59 UTC, bigfanoftim commented on songhyun/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- `.gitignore`에 등록하기 전에 한번이라도 Git으로 관리(add, commit 등)된 파일은 계속해서 Git에 의해 추적됩니다.
- 따라서 이를 해결하기 위해서는 다음과 같이 Git의 캐시를 삭제해야 합니다.
    - `git rm —cached 파일명`
- 삭제 후에는 수정된 사항을 다시 리모트에 푸시해야 합니다.

2022-11-02 06:00 UTC, bigfanoftim commented on songhyun/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
되도록이면 github에서 제공하는 gui에 의존하지 마시고 본인 개발환경에서 해결해 주세요.

2022-11-02 06:00 UTC, bigfanoftim approved these changes
LGTM 👍 
마지막으로 남겨드린 리뷰 한번 확인해주세요~

2022-11-02 06:01 UTC, merged