[지송현] Assignment 3 | Westagram Backend Project - 게시글 등록하기
wecode-bootcamp-korea/39-backend-westagram-1 pull request #20
Opened 2022-11-04 02:00 UTC by applleeee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 게시글 db 저장
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 입력받은 게시글 db에 저장

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-04 02:13 UTC, bigfanoftim reviewed
Files changed를 확인해보신걸까요?

현재 작성하신 코드의 상황을 살펴보면 다음과 같습니다.
1. 이전 PR에서 회원가입 API 구현
2. 현재 PR에서 회원가입 API를 지우고 게시글 등록 구현

지금 개발하시고 있는 브랜치를 삭제 후 main 브랜치로 돌아가서  git pull origin main 명령어로 로컬 main 브랜치를 업데이트 해주세요.
이후에 로컬 main에서 새롭게 assignment3에 해당하는 브랜치를 생성하여 코드를 추가해 주세요.

2022-11-04 04:52 UTC, bigfanoftim requested changes
- migration 관련 파일들이 보이지 않네요~
- `db/migrations` 디렉토리 하위에 `*.sql` 파일들은 데이터베이스의 형상관리를 위해서 GitHub에 올려서 다른 개발자들과 공유하여 같은 데이터베이스 환경을 구축해서 개발할 수 있도록 만들어줘야 합니다. 따라서 `db/migrations` 하위 `*.sql` 파일들은 GitHub에 올려서 관리해주세요.

2022-11-07 04:37 UTC, bigfanoftim requested changes

2022-11-07 04:37 UTC, bigfanoftim commented on songhyun/db/migrations/20221104082404_users.sql
> +DROP TABLE users;
해당 마이그레이션 파일은 과제2에서 생성했엇을텐데 과제3 PR에 올라온 것을 보면 과제2로 부터 브랜치를 만드셨던게 아닌가 싶네요. 과제2에서 리뷰 이후 업데이트된 내용이 있으시다면 아래의 순서를 따라 현재 과제3에 해당하는 브랜치를 업데이트 후 다시 푸시해주세요.
- 로컬의 main(혹은 master) 브랜치로 이동합니다. `git checkout main(master)`
- 리모트 main 브랜치에 머지된 내용을 로컬로 가져옵니다. `git pull origin main`
- 개발하고 있는 브랜치로 이동합니다. `git checkout branch-name`
- main에 새로 추가된 내용을 현재 브랜치로 병합합니다. `git merge main`

2022-11-07 06:55 UTC, applleeee commented on songhyun/db/migrations/20221104082404_users.sql
> +DROP TABLE users;
main 브랜치를 확인해 봤는데 main에도 위의 users.sql 파일이 보이지 않습니다. 그럼 과제2로 돌아가서 파일 생성 후 다시 메인으로 머지 후 과제3를 생성해야 할까요?

2022-11-09 02:55 UTC, bigfanoftim approved these changes

2022-11-09 02:55 UTC, bigfanoftim commented on songhyun/db/migrations/20221104082404_users.sql
> +DROP TABLE users;
확인해보니 Assignment 2에 해당하는 PR에 users migration을 추가안해주셨군요~

이 상태 그대로 머지하겠습니다~

2022-11-09 02:55 UTC, merged