[이명석] Assignment 6: Express API - CRUD (유저 게시글 수정하기)
wecode-bootcamp-korea/39-backend-westagram-1 pull request #24
Opened 2022-11-04 08:19 UTC by myeongseoklee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 게시글 수정하기 엔드포인트
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 성공시 201 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이 엔드포인트도 한 단락의 Query문으로 구현해야 할까요...?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-04 08:25 UTC, bigfanoftim commented
> 이 엔드포인트도 한 단락의 Query문으로 구현해야 할까요...?

명석님! 이전에는 쿼리문을 하나로 합쳐달라고 리뷰를 드렸지만 그것이 절대 모든 상황에 해당하지는 않습니다.
또한 이번에 개발하신 API는 UPDATE를 위한 것이기 때문에 다시 한 번 SELECT로 불러올 필요는 없습니다.
하지만 이것 또한 프로젝트마다 어떻게 데이터를 주고 받으며 처리해나갈지에 따라 다르다고 말씀드릴 수 있습니다.
다만 업데이트를 하는 경우에는 제대로 수정을 했는지 판단하기 위해서 업데이트된 row 수를 검증하는 작업은 꼭 필요합니다. 
UPDATE 쿼리의 결과를 console.log()로 확인해 보시고 거기서 검증할 수 있는 데이터가 반환되는지 확인 후 코드를 수정해 보세요~

2022-11-04 11:49 UTC, myeongseoklee commented
![스크린샷 2022-11-04 오후 6 02 49](https://user-images.githubusercontent.com/109528794/199965266-a8bdd04d-0e52-4d16-90e8-e1ab3d13c6b9.png)

patch 메소드 요청에 따른 수정 내용을 콘솔로 찍어보았습니다.

콘솔에서 
affectedRows : 1
changedRows : 1
가 확인되었고

postman에서 response body에 담긴 변경된 데이터도 확인되었습니다.

그러면 코드를 수정할 필요가 없을까요?

2022-11-07 05:43 UTC, bigfanoftim commented
> ![스크린샷 2022-11-04 오후 6 02 49](https://user-images.githubusercontent.com/109528794/199965266-a8bdd04d-0e52-4d16-90e8-e1ab3d13c6b9.png)
> 
> patch 메소드 요청에 따른 수정 내용을 콘솔로 찍어보았습니다.
> 
> 콘솔에서 affectedRows : 1 changedRows : 1 가 확인되었고
> 
> postman에서 response body에 담긴 변경된 데이터도 확인되었습니다.
> 
> 그러면 코드를 수정할 필요가 없을까요?

변경된 데이터 값 자체는 필요가 없으니 response로 affectedRows와 메세지 정도 반환해주면 좋을 것 같아요~

2022-11-07 05:46 UTC, myeongseoklee commented
과제에서 변경된 데이터 값 자체를 응답으로 보내라는 것으로 잘못 이해한 것 같습니다! 해당 내용 수정하겠습니다!

2022-11-07 06:26 UTC, bigfanoftim requested changes
간단한 수정 사항 요청드립니다. 빠르게 수정 후 Push 해주세요!

2022-11-07 06:26 UTC, bigfanoftim commented on myeongseok/app.js
> +  res.status(201).json({ message: `affectedRows, ${result.affectedRows}` });
```suggestion
  res.status(200).json({ 
    message: 'success',
    affectedRows: result.affectedRows
  });
```

2022-11-07 06:53 UTC, myeongseoklee commented on myeongseok/app.js
> +  res.status(201).json({ message: `affectedRows, ${result.affectedRows}` });
수정 완료하였습니다!

2022-11-07 06:59 UTC, myeongseoklee commented
conflict 해결 하였습니다!

2022-11-07 07:16 UTC, bigfanoftim requested changes

2022-11-07 07:16 UTC, bigfanoftim commented on myeongseok/app.js
> +  const { id, content, user_id } = req.body;
여기도 user_id가 있네요~ 있더라도 userId 라고 네이밍 컨벤션을 통일해 주세요~

2022-11-08 02:34 UTC, Jon9Beom commented
LGTM 👍

2022-11-08 02:34 UTC, merged