[박상욱-team1] Assignment2 : Express API - 유저 회원가입 하기
wecode-bootcamp-korea/39-backend-westagram-1 pull request #25
Opened 2022-11-04 09:02 UTC by pso0301

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- git 개념 잡는게 너무 힘듭니다. 머리로 이미지메이킹이 힘드네요.ㅠㅠ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
![데이터출력값](https://user-images.githubusercontent.com/112918378/199933838-058721e0-f04f-40f8-9e16-4c442fdb5804.png)

2022-11-04 09:51 UTC, bigfanoftim requested changes

2022-11-04 09:51 UTC, bigfanoftim commented on sanguk/app.js
> +    //console.log(req)
```suggestion
```
개발 시 테스트 용으로 작성한 불필요한 `console.log()`는 전부 지워주세요.

2022-11-04 09:51 UTC, bigfanoftim commented on sanguk/app.js
> +app.post("/users", async (req,res,next)=>{
```suggestion
app.post("/users/signup", async (req,res,next)=>{
```
주소를 좀 더 정확하게 적어주시면 좋을 것 같아요~!

2022-11-04 13:51 UTC, pso0301 commented on sanguk/app.js
> +    //console.log(req)
^^ 다음에는 이 부분도 기억하고 신경 쓰겠습니다

2022-11-04 13:52 UTC, pso0301 commented on sanguk/app.js
> +app.post("/users", async (req,res,next)=>{
아 저거는 생각을 미처 못 한거 같습니다. 다음에 과제 할때 한번 생각하고 업데이트 하도록 하겠습니다.^^

2022-11-07 01:51 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-07 01:51 UTC, merged