[이명석] Assignment 8: Express API - CRUD (좋아요 누르기)
wecode-bootcamp-korea/39-backend-westagram-1 pull request #28
Opened 2022-11-06 09:22 UTC by myeongseoklee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 좋아요 누르기 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-07 07:00 UTC, myeongseoklee commented
충돌 해결했습니다!

2022-11-07 07:20 UTC, bigfanoftim requested changes

2022-11-07 07:20 UTC, bigfanoftim commented on myeongseok/app.js
> +  const { title, post_image, content, user_id } = req.body;
```suggestion
  const { title, postImageUrl, content, user_id } = req.body;
```
- JavaScript에서는 기본적으로 `snake_case`가 아닌 `CamelCase`로 작성합니다.
- 또한 snake_case, CamelCase를 뒤죽박죽 섞어서 사용하면 안됩니다.
- 하나의 컨벤션으로 통일해서 작성해 주세요.

2022-11-07 07:20 UTC, bigfanoftim commented on myeongseok/db/migrations/20221104143357_update_posts_table.sql
> +ALTER TABLE posts ADD post_image varchar(1000) NOT NULL AFTER title
```suggestion
ALTER TABLE posts ADD post_image_url varchar(1000) NOT NULL AFTER title
```
image 파일을 저장하는 것이 아니라 주소를 저장하는 것이기 때문에 정확히 적어주는 것이 중요합니다~

2022-11-07 07:22 UTC, myeongseoklee commented on myeongseok/app.js
> +  const { title, post_image, content, user_id } = req.body;
세세하게 짚어주셔서 감사합니다!!

2022-11-07 07:33 UTC, myeongseoklee commented on myeongseok/db/migrations/20221104143357_update_posts_table.sql
> +ALTER TABLE posts ADD post_image varchar(1000) NOT NULL AFTER title
네 감사합니다! dbmate 수정 및 해당 column이 사용된 query문의 column 이름도 수정하였습니다!

2022-11-08 08:04 UTC, Jon9Beom commented on myeongseok/app.js
> +  const { title, postImageUrl, content, user_id } = req.body;
```suggestion
  const { title, postImageUrl, content, userId } = req.body;
```
snake_case가 아닌 camelCase로 작성하고 받을 수 있게 해주세요~

2022-11-08 08:04 UTC, Jon9Beom commented on myeongseok/app.js
> +    [title, postImageUrl, content, user_id]
```suggestion
    [title, postImageUrl, content, userId]
```

2022-11-08 08:04 UTC, Jon9Beom commented on myeongseok/app.js
>    res.status(201).json({ message: 'postCreated' });
```suggestion
  return res.status(201).json({ message: 'postCreated' });
```

2022-11-08 08:04 UTC, Jon9Beom commented on myeongseok/app.js
> +  const { user_id, post_id } = req.body;
```suggestion
  const { userId, postId } = req.body;
```

2022-11-08 08:04 UTC, Jon9Beom commented on myeongseok/app.js
> +    VALUES (?, ?)`,
혹시 동일한 유저가 동일한 게시글에 대해 한 번 더 좋아요를 누르면 어떻게 되나요?

이를 방지 하기 위해선 javascript code를 통해 해당 로직을 처리할 수 도 있겠지만 likes table에 user_id, post_id가 묶여서 UNIQUE 제약 조건이 걸어주는 방법이 있습니다. table에 제약 조건을 추가하는 `CONSTRAINT unique_likes UNIQUE (user_id, post_id)` 와 같은 SQL 코드가 추가되면 됩니다.

해당 코드는 기존의 migration 파일을 수정하는 것이 아닌 새로이  migration 파일을 만든 뒤 `ALTER TABLE` 을 사용하여 작성해주세요-!

2022-11-08 08:08 UTC, myeongseoklee commented on myeongseok/app.js
> +    VALUES (?, ?)`,
세심한 체크 감사합니다^^

2022-11-08 08:15 UTC, myeongseoklee commented on myeongseok/app.js
> +    VALUES (?, ?)`,
지금 상태에서는 동일한 유저가 좋아요를 한 번 더 누를 경우 중복된 데이터가 적재될 것 같습니다. 둘을 묶어 동일한 데이터 조합이 적재되지 않도록 수정후 migration 하겠습니다!

2022-11-08 08:44 UTC, Jon9Beom commented
LGTM 👍

2022-11-08 08:44 UTC, merged