[오현상] Authentication(인증/인가) 1~3
wecode-bootcamp-korea/39-backend-westagram-1 pull request #34
Opened 2022-11-09 05:29 UTC by MatheGoD

## 수정 사항 간략한 한줄 요약
- 인증/인가 Assignment 1~3 구현
		 
## 수정 사항들 자세한 내용
- 회원가입 기능 구현 (입력된 비밀번호 암호화)
- 로그인 기능 구현 (입력된 아이디 및 비밀번호 검사 및 토큰 발급)
- 토큰 값을 비교 후 토큰 값이 맞다면 게시글 생성
  (우선 게시글 생성 부분만 로직을 만들어두었습니다 / 멘토님의 리뷰 후 수정/라이크 등 권한이 필요할만 한 곳에 로직을 붙일 예정입니다) 

![암호화된 비밀번호](https://user-images.githubusercontent.com/110371295/200746444-68e2e560-1ae2-4764-ae95-ba6a87bcfc47.png)
![로그인 성공](https://user-images.githubusercontent.com/110371295/200746485-a66fac49-9d2d-4737-8e49-e3893a55f9a7.png)
![로그인 실패](https://user-images.githubusercontent.com/110371295/200746496-207cd969-96d6-4269-9cd3-4a99aa4c2a7a.png)
![게시글 등록성공(1)](https://user-images.githubusercontent.com/110371295/200746514-bf5e74fd-f9f3-414e-b966-1dc64b67dd71.png)
![게시글 등록성공(2)](https://user-images.githubusercontent.com/110371295/200746526-b05d93d4-e4db-455e-9027-78cf2ffb7811.png)
![게시글 등록실패](https://user-images.githubusercontent.com/110371295/200746540-00ad8b28-5972-45d1-8afa-169b7f5a1e0e.png)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-09 05:30 UTC, MatheGoD commented
인가 부분에 대해서는 우선 게시글 등록에 대한 리뷰를 받고 나서 추가할 예정입니다.

2022-11-09 05:47 UTC, bigfanoftim requested changes

2022-11-09 05:47 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  console.log(userPost);
```suggestion
```

2022-11-09 05:47 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +      INSERT INTO users(
실제로 user 데이터를 insert하기 전에 이메일이 중복되지는 않는지 검증하는 로직을 더해보세요!

2022-11-09 05:47 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  const validity = await appDataSource.query(
```suggestion
  const [user] = await appDataSource.query(
```
나오는 데이터는 결국 user 데이터일 뿐입니다. 추가로 다음과 같이 작성하면 리스트에서 하나의 요소만 가져올 수 있습니다.

2022-11-09 05:47 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  console.log(validity);
리뷰 요청하시기 전에 테스트를 하기 위해 작성된 코드들은 전부 지워주세요.

2022-11-09 09:04 UTC, bigfanoftim requested changes
잘하셨습니다 현상님!! 자잘한 수정 사항이니 빠르게 push 후 마무리 해봅시다~

2022-11-09 09:04 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +const secretKey = process.env.secretKey;
```suggestion
const secretKey = process.env.SECRET_KEY;
```
기존에 환경 변수 네이밍 컨벤션과 맞춰서 다시 작성해 주세요~

2022-11-09 09:04 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +const saltRounds = 12;
```suggestion
const saltRounds = process.env..;
```
개인적으로 이것도 환경변수로 관리하면 더 좋을 것 같아요~

2022-11-09 09:04 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +  if (check.user == 1) {
```suggestion
  if (check.user) {
```
단순 truthy or falsy 판단이라면 다음과 같이 간결하게 작성할 수 있을 것 같습니다!

2022-11-09 09:04 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +    WHERE email = ?;
매칭되는 이메일이 없을 때의 에러 핸들링이 필요해 보입니다.

2022-11-09 09:04 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +    if (check === true) {
```suggestion
    if (check) {
```
여기도 마찬가지입니다.

2022-11-09 09:04 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +        email: email,
```suggestion
```
이메일은 사실 워낙 퍼블릭하게 사용되는 정보이긴 하나 굳이 있을 필요는 없으니 지워주세요~

2022-11-11 06:22 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-11 06:22 UTC, merged