[이명석] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/39-backend-westagram-1 pull request #7
Opened 2022-11-02 07:20 UTC by myeongseoklee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 회원가입 엔드포인트 및 회원가입 데이터 DB 입력 (by postman)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 엔드포인트 api 
- 성공시 201 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 머지된 assignment1의 내용을 assignment2에 번영할 때, git pull origin main 명령을 내리면 될까요?
- 앞으로 만드는 과제의 브랜치를 assignment3 ,4 이런 식으로 새로 만들어서 작업하되 그 내용들을 push. PR할 때, main으로 해야하나요 아니면 assignment2로 해야하나요? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-02 07:32 UTC, bigfanoftim commented
Conflict 해결 부탁드립니다.

2022-11-02 07:56 UTC, bigfanoftim requested changes

2022-11-02 07:56 UTC, bigfanoftim commented on myeongseok/db/migrations/20221101235627_posts.sql
> +DROP TABLE posts
- 과제와 상관없거나 해당되지 않는 코드가 Push 되었습니다. 이후 과제에서 진행되는 코드는 그 과제에 맞는 PR에서 Push 해주세요.

2022-11-02 07:56 UTC, bigfanoftim commented on myeongseok/db/migrations/20221101235627_posts.sql
> +DROP TABLE posts
- 과제와 상관없거나 해당되지 않는 코드가 Push 되었습니다. 이후 과제에서 진행되는 코드는 그 과제에 맞는 PR에서 Push 해주세요.

2022-11-02 07:56 UTC, bigfanoftim commented on myeongseok/db/migrations/20221101235621_users.sql
> +  email VARCHAR(200) NOT NULL,
- 해당 컬럼은 중복되면 안되는 데이터를 저장하는 컬럼입니다. 따라서 unique contraint를 추가해주셔야 합니다.

2022-11-02 07:56 UTC, bigfanoftim commented on myeongseok/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
- `schema.sql`은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 `.gitignore`에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-11-03 02:19 UTC, bigfanoftim commented on myeongseok/db/migrations/20221101235621_users.sql
> +  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
id는 primary key라 unique 옵션을 따로 줄 필요가 없습니다.

2022-11-03 02:19 UTC, bigfanoftim commented on myeongseok/db/migrations/20221101235621_users.sql
> +  name VARCHAR(50) NOT NULL UNIQUE,
이름은 중복될 수 있지 않나요?

2022-11-03 05:10 UTC, myeongseoklee commented on myeongseok/db/migrations/20221101235621_users.sql
> +  name VARCHAR(50) NOT NULL UNIQUE,
아.. 처음에 unique 제약조건을 생각없이 id, name, email 컬럼에 넣은 것 같습니다..

id는 primary키니까 어차피 중복이 안되고, name은 동명이인일 수 있으니까 unique 제약 삭제했습니다!
감사합니다.

2022-11-03 05:30 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-03 05:30 UTC, merged