[오현상-team1] Assignment3 : Express API - 게시글 등록하기
wecode-bootcamp-korea/39-backend-westagram-1 pull request #8
Opened 2022-11-02 08:04 UTC by MatheGoD

[](url)>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 게시글 등록하기
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- dbmate new COMMAND를 이용하여 posts 테이블 생성
- 게시글 등록 4개 이상(make_post)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-02 08:05 UTC, MatheGoD commented
[](url)
![users and posts](https://user-images.githubusercontent.com/110371295/199433453-0595b5f6-83d7-4557-be53-2729c383a1c8.png)

2022-11-02 08:49 UTC, bigfanoftim requested changes

2022-11-02 08:49 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +
중복된 코드로 보여지네요.

2022-11-02 08:49 UTC, bigfanoftim commented on HYUNSANG_OH/app.js
> +app.post("/make_post", async (req,res,next) =>{
```suggestion
```
- Post 메소드는 주로 새로운 리소스를 생성할 때 사용되는 메소드입니다. 이미 메소드 이름에 충분히 의미가 부여되었으니 URI는 요청에 맞는 자원을 기준으로 작성해 주세요.
    
    ```jsx
    // BAD ❌
    POST :3000/make/post
    POST :3000/create_post
    POST :3000/make_post
    
    // GOOD ✅
    POST :3000/post
    ```

2022-11-02 09:05 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +
엇 바로 지우겠습니다!

2022-11-02 09:05 UTC, MatheGoD commented on HYUNSANG_OH/app.js
> +app.post("/make_post", async (req,res,next) =>{
감사합니다..네이밍 센스라는 것은 확실히..어렵네요..

2022-11-03 02:20 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-03 02:20 UTC, merged